const TYPES  = {
    UPDATE_DEVICE_TYPE: "UPDATE_DEVICE_TYPE",
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGIN_USER: 'LOGIN_USER',
    LOGOUT_USER: 'LOGOUT_USER',
    USER_DETAILS: 'USER_DETAILS',
    BUY_ITEMS: 'BUY_ITEMS'
}

export default TYPES