export const APP_ENV = {
  INFURA_ID: process.env.NEXT_PUBLIC_INFURA_ID,
  API_URL: process.env.NEXT_PUBLIC_API_URL,
  S3_ASSET_URL: process.env.NEXT_PUBLIC_ASSET_S3,
  BASE_CURRENCY_CODE: process.env.NEXT_PUBLIC_ADMIN_BASE_CURRENCY_CODE,
  CUSTOMER_WEB_URL: process.env.NEXT_PUBLIC_CUSTOMER_WEB_URL,
  SIGN_MESSAGE: process.env.NEXT_PUBLIC_SIGN_MESSAGE,
  NETWORK_TYPE: process.env.NEXT_PUBLIC_NETWORK_TYPE,
  SHOW_THEME:process.env.NEXT_PUBLIC_SHOW_THEME_CUSTOMIZATION
}
