const TYPES = {
  UPDATE_DEVICE_TYPE: 'UPDATE_DEVICE_TYPE',
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  USER_DETAILS: 'USER_DETAILS',
  THEME_DATA: 'THEME_DATA',
  REFRESH_API: 'REFRESH_API',
  SET_PERMISSION: 'SET_PERMISSION',
  PREFERANCE_DATA: 'PREFERANCE_DATA',
  ADMIN_CONFIG: 'ADMIN_CONFIG'
}

export default TYPES
